/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-05-01 at 23:33:35 UTC 
 * Modify at your own risk.
 */

package com.eventzapp.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("eventfatchparams_id") @com.google.api.client.json.JsonString
  private java.lang.Long eventfatchparamsId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> friendids;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> likeids;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer orderpreference;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("totalmatchmethod_id") @com.google.api.client.json.JsonString
  private java.lang.Long totalmatchmethodId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long uid;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEventfatchparamsId() {
    return eventfatchparamsId;
  }

  /**
   * @param eventfatchparamsId eventfatchparamsId or {@code null} for none
   */
  public User setEventfatchparamsId(java.lang.Long eventfatchparamsId) {
    this.eventfatchparamsId = eventfatchparamsId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getFriendids() {
    return friendids;
  }

  /**
   * @param friendids friendids or {@code null} for none
   */
  public User setFriendids(java.util.List<java.lang.Long> friendids) {
    this.friendids = friendids;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getLikeids() {
    return likeids;
  }

  /**
   * @param likeids likeids or {@code null} for none
   */
  public User setLikeids(java.util.List<java.lang.Long> likeids) {
    this.likeids = likeids;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public User setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOrderpreference() {
    return orderpreference;
  }

  /**
   * @param orderpreference orderpreference or {@code null} for none
   */
  public User setOrderpreference(java.lang.Integer orderpreference) {
    this.orderpreference = orderpreference;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotalmatchmethodId() {
    return totalmatchmethodId;
  }

  /**
   * @param totalmatchmethodId totalmatchmethodId or {@code null} for none
   */
  public User setTotalmatchmethodId(java.lang.Long totalmatchmethodId) {
    this.totalmatchmethodId = totalmatchmethodId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUid() {
    return uid;
  }

  /**
   * @param uid uid or {@code null} for none
   */
  public User setUid(java.lang.Long uid) {
    this.uid = uid;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
